### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by hamada456** [hamada456/protospace-31719#1]
自身のProtoSpaceのURL
https://github.com/hamada456/protospace-31719
本番環境(Heroku)のURL
https://protospace-31719.herokuapp.com/

**Comment by naokihayasan127** [comment]
濱田さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
